version: 2

sources:
  - name: raw
    description: "Raw data ingested by dlt"
    schema: raw
    tables:
      - name: orders
        identifier: orders
        description: "Raw orders data"
      - name: customers
        identifier: customers
        description: "Raw customers data"