name: Total Revenue by Category
description: Total Revenue by Category
tableName: customer_retention_churn_prevention
updatedAt: '2026-04-04T04:20:28.000Z'
metricQuery:
  exploreName: customer_retention_churn_prevention
  dimensions:
  - customer_retention_churn_prevention_category
  metrics: &id001
  - customer_retention_churn_prevention_total_revenue_sum
  filters: {}
  sorts:
  - fieldId: customer_retention_churn_prevention_total_revenue_sum
    descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      xField: customer_retention_churn_prevention_category
      yField: *id001
    eChartsConfig:
      axes:
      - position: bottom
      - position: left
        name: Total Revenue
      series:
      - type: bar
        name: Total Revenue
        encode:
          xRef:
            field: customer_retention_churn_prevention_category
          yRef:
            field: customer_retention_churn_prevention_total_revenue_sum
slug: total_revenue_by_category
tableConfig:
  columnOrder:
  - customer_retention_churn_prevention_category
  - customer_retention_churn_prevention_total_revenue_sum
spaceSlug: home
version: 1
