name: Total Revenue
description: Total Revenue
tableName: customer_retention_churn_prevention
updatedAt: '2026-04-04T04:20:28.000Z'
metricQuery:
  exploreName: customer_retention_churn_prevention
  dimensions: []
  metrics:
  - customer_retention_churn_prevention_total_revenue_sum
  filters: {}
  sorts: []
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    bigNumber: customer_retention_churn_prevention_total_revenue_sum
    bigNumberLabel: Total Revenue
slug: total_revenue
tableConfig:
  columnOrder:
  - customer_retention_churn_prevention_total_revenue_sum
spaceSlug: home
version: 1
